framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    serializer:
        enabled: true
    property_info:
        enabled: true
    validation: ~
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: 'doctrine://default'
                options:
                    use_notify: true
                    check_delayed_interval: 1000
            failed:
                dsn: 'doctrine://default'
                options:
                    queue_name: failed
        routing:
            'App\Message\SyncTickTickMessage': async
